build.sbt, plugin/src/main/scala/scalafix/sbt/ScalafixPlugin.scala, plugin/src/main/scala/scalafix/sbt/ScalafixTestkitPlugin.scala, plugin/src/test-project-template/project/plugins.sbt, plugin/src/test-project-template/project/project/plugins.sbt
=> Upgrade to scalafix v0.6.0-M12

project/build.properties
=> Downgrade to sbt 1.1

src/main/scala/scalafix/internal/sbt/ScalafixCompletions.scala
Fixes https://github.com/scalacenter/scalafix/issues/417
=> Fix handling of absolute file:<rule>

build.sbt, project/Dependencies.scala, src/main/scala/scalafix/internal/sbt/ScalafixCoursier.scala, src/main/scala/scalafix/internal/sbt/ScalafixInterface.scala, src/main/scala/scalafix/sbt/ScalafixEnable.scala, src/main/scala/scalafix/sbt/ScalafixFailed.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/basic/build.sbt, src/sbt-test/sbt-scalafix/inconfig/build.sbt, src/test/scala/scalafix/internal/sbt/SbtCompletionsSuite.scala, src/test/scala/scalafix/internal/sbt/ScalafixAPISuite.scala
This version makes it possible to validate before running
fullClasspath.value
=> Upgrade to M19

src/main/scala/scalafix/internal/sbt/ScalafixCoursier.scala, src/main/scala/scalafix/internal/sbt/ScalafixInterface.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/test/scala/scalafix/internal/sbt/SbtCompletionsSuite.scala, src/test/scala/scalafix/internal/sbt/ScalafixAPISuite.scala
fixes https://github.com/scalacenter/scalafix/issues/929
=> Use custom resolvers

project/Dependencies.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala
hopefully fixes https://github.com/scalacenter/scalafix/issues/930
=> Upgrade coursier-small to 1.3.3

.travis.yml, build.sbt, project/Dependencies.scala, project/build.properties, project/project/plugins.sbt, src/sbt-test/sbt-scalafix/basic/build.sbt, src/sbt-test/sbt-scalafix/basic/project/project/plugins.sbt, src/sbt-test/sbt-scalafix/cross-build/project/project/plugins.sbt, src/sbt-test/sbt-scalafix/dependency/project/project/plugins.sbt, src/sbt-test/sbt-scalafix/inconfig/build.sbt, src/sbt-test/sbt-scalafix/inconfig/project/project/plugins.sbt, src/sbt-test/sbt-scalafix/root-validation/build.sbt, src/sbt-test/sbt-scalafix/root-validation/project/project/plugins.sbt, src/sbt-test/sbt-scalafix/suppress/project/project/plugins.sbt
Also makes the sbt build compatible with the coursier sbt launcher.
=> Upgrade to Scalafix 0.9.6

build.sbt, project/Dependencies.scala, project/plugins.sbt, src/main/scala/scalafix/internal/sbt/ScalafixCoursier.scala, src/main/scala/scalafix/sbt/BuildInfo.scala, src/sbt-test/sbt-scalafix/basic/build.sbt, src/sbt-test/sbt-scalafix/basic/project/plugins.sbt, src/sbt-test/sbt-scalafix/cross-build/build.sbt, src/sbt-test/sbt-scalafix/cross-build/project/plugins.sbt, src/sbt-test/sbt-scalafix/dependency/project/plugins.sbt, src/sbt-test/sbt-scalafix/inconfig/build.sbt, src/sbt-test/sbt-scalafix/inconfig/project/plugins.sbt, src/sbt-test/sbt-scalafix/root-validation/build.sbt, src/sbt-test/sbt-scalafix/root-validation/project/plugins.sbt, src/sbt-test/sbt-scalafix/scalafixEnable/project/plugins.sbt, src/sbt-test/sbt-scalafix/suppress/project/plugins.sbt, src/test/scala/scalafix/internal/sbt/SbtCompletionsSuite.scala
https://github.com/scalacenter/scalafix/releases/tag/v0.9.12
=> Upgrade to Scalafix 0.9.12

src/main/scala/scalafix/internal/sbt/ShellArgs.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/explicit-files/.scalafix.conf, src/sbt-test/sbt-scalafix/explicit-files/build.sbt, src/sbt-test/sbt-scalafix/explicit-files/explicit/src/main/scala/KO.scala, src/sbt-test/sbt-scalafix/explicit-files/explicit/src/main/scala/OK.scala, src/sbt-test/sbt-scalafix/explicit-files/project/plugins.sbt, src/sbt-test/sbt-scalafix/explicit-files/project/project/plugins.sbt, src/sbt-test/sbt-scalafix/explicit-files/test
I might be missing something, but it looks like https://github.com/scalacenter/sbt-scalafix/commit/4dbaf1ece9a67ab686cf5c4e12483298996005de#diff-b6db8e3499369917214568aee2dd0960R222 never worked.
=> fix -f/--files

src/main/scala/scalafix/sbt/BuildInfo.scala
Follow-up of https://github.com/scalacenter/sbt-scalafix/pull/112#issuecomment-635283005
Closes https://github.com/scalacenter/sbt-scalafix/pull/112
=> remove fallbacks creating confusions about which versions are used

.scala-steward.conf
Same rationale as https://github.com/scalacenter/scalafix/pull/1159
=> bi-weekly scala steward updates to reduce noise

src/main/scala/scalafix/sbt/ScalafixPlugin.scala
=> scalafixAll tweaks

.github/dependabot.yml
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot
=> ask dependabot to upgrade github actions

src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-1.4/build-lint/build.sbt, src/sbt-test/sbt-1.4/build-lint/project/build.properties, src/sbt-test/sbt-1.4/build-lint/project/plugins.sbt, src/sbt-test/sbt-1.4/build-lint/test
Follows https://github.com/scalacenter/sbt-scalafix/pull/168/commits/47af7400999aa10ede62a1676ee497ff80c5bded
Originally spotted in https://github.com/scalameta/metals/pull/2860/files#r646017259
=> ensure keys do not need to be silenced with excludeLintKeys

.scala-steward.conf
https://github.com/scalacenter/sbt-scalafix/blob/e482b26d086d5bd0424d78c613bb6b704bbb732e/src/sbt-test/skip-windows/caching/test#L176-L181
=> don't upgrade example rules as this can bring false negatives in scripted

project/Dependencies.scala
Attempt at fixing https://github.com/scalacenter/scalafix/issues/1510
=> bump coursier

.scala-steward.conf
Closes https://github.com/scalacenter/sbt-scalafix/pull/263
=> don't bump JGit to keep Java 8 compatibility

src/main/scala/scalafix/internal/sbt/DependencyRule.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala
Follows https://github.com/scalacenter/sbt-scalafix/pull/282
See commit messages
=> more `sbt scalafix dependency:` tweaks

src/test/scala/scalafix/internal/sbt/ScalafixAPISuite.scala
https://github.com/scalacenter/example-scalafix-rule/issues/11
=> ch.epfl.scala::example-scalafix-rule:3.0.0 is now available

LICENSE
Follow up of https://github.com/scalacenter/scalafix/pull/1833
=> Add same license as scalafix

build.sbt, src/sbt-test/sbt-1.5/scalafixEnable/build.sbt, src/sbt-test/sbt-scalafix/basic/build.sbt, src/sbt-test/sbt-scalafix/inconfig/build.sbt, src/sbt-test/sbt-scalafix/root-validation/build.sbt, src/sbt-test/sbt-scalafix/semanticdb-enabled/build.sbt, src/sbt-test/skip-java17/scalafixResolvers/build.sbt
https://github.com/scalacenter/scalafix/issues/1936
=> build with and test against Scala 2.12.19

src/main/scala/scalafix/internal/sbt/ScalafixInterface.scala
Fixes https://github.com/scalacenter/scalafix/issues/1955
=> Rename scalafixBinaryScalaVersion to scalafixScalaBinaryVersion

.github/workflows/ci.yml, .github/workflows/release.yml
Follows https://github.com/scalacenter/sbt-scalafix/pull/395, that missed some occurences
=> move away from deprecated olafurpg/setup-scala

src/sbt-test/sbt-scalafix/semanticdb-enabled/build.sbt
https://github.com/scalacenter/scalafix/issues/1983
=> test against Scala 2.13.14

src/main/scala/scalafix/sbt/ScalafixPlugin.scala
Fixes https://github.com/scalacenter/scalafix/issues/2007
Follows https://github.com/scalacenter/sbt-scalafix/pull/404
=> ignore missing credential files instead of failing hard

project/Dependencies.scala, src/main/scala/scalafix/internal/sbt/ScalafixInterface.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/resolvers/project/plugins.sbt, src/sbt-test/sbt-scalafix/scalafixEnable/build.sbt, src/sbt-test/skip-windows/caching/test
Towards https://github.com/scalacenter/scalafix/issues/1680
Prepares for https://github.com/scalacenter/scalafix/pull/2023
=> leverage cli_3.x.y

project/Dependencies.scala, src/test/scala/scalafix/internal/sbt/SbtCompletionsSuite.scala, src/test/scala/scalafix/internal/sbt/ScalafixAPISuite.scala
=> scalafix 0.13.0

.github/workflows/ci.yml, .github/workflows/release.yml
https://github.com/actions/runner-images/issues/10767
=> ubuntu-latest now points to 24.04 which does not include sbt

src/sbt-test/sbt-scalafix/explicit-files/build.sbt, src/sbt-test/sbt-scalafix/semanticdb-enabled/build.sbt
https://github.com/scalameta/scalameta/issues/4128#issuecomment-2585373710
=> test current scalafix against 2.13.16 sources

project/Dependencies.scala
https://github.com/scalacenter/sbt-scalafix/pull/469#discussion_r1962547396
=> scalafix 0.14.2

bin/test-release.sh
Follows https://github.com/scalacenter/sbt-scalafix/pull/440
=> cs does not know sbt milestones do not guarantee binary compat

src/main/scala/scalafix/internal/sbt/ScalafixInterface.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala
Troubleshoot https://github.com/scalacenter/scalafix/issues/1848
=> scalacOptions tweaks

.github/workflows/ci.yml
Follows https://github.com/scalacenter/sbt-scalafix/pull/507 where I concluded too quick that the windows timeout was transient.
The problem was that the windows CI started defaulting to Java 17 because of windows-latest moving from [Windows Server 2022](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md) to [Windows Server 2025](https://github.com/actions/runner-images/blob/main/images/windows/Windows2025-Readme.md), causing sbt-dotenv to fail (it's known not to run there but wasn't explicitly excluded because windows assumed to run on Java 8), and the scripted harness to crash, leading to timeouts.
```
skipping, JVM is already installed in C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\17.0.16-8\x64
...
Error: …
```
=> fix windows CI by bringing back to JDK8 explicitly

project/Dependencies.scala
Closes https://github.com/scalacenter/sbt-scalafix/pull/497
Closes https://github.com/scalacenter/scalafix/issues/2270
=> bump jgit to fix CVE-2025-4949
