build.sbt, src/main/scala/scalafix/sbt/ScalafixInterface.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/basic/.scalafix.conf, src/sbt-test/sbt-scalafix/basic/build.sbt, src/sbt-test/sbt-scalafix/basic/tests/src/test/scala/tests/CheckSuite.scala, src/test/scala/scalafix/internal/sbt/ScalafixInterfaceSuite.scala
Fixes #7.
This PR improves support for custom rules that are published to Maven
Central. This functionality is required for rules like
scala-collection-compat. We do a best-effort to avoid redundant
dependency fetching of `scalafixDependencies` by caching the results
in an in-memory map. In the future, it would make sense to expose more
powerful APIs in scalafix to cache classloaders between invocations.
=> Support scalafixDependencies

src/main/scala/scalafix/sbt/ScalafixFailed.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala
This makes th output from failed runs cleaner by eliminating redudant
lines. The change is particularly welcome when running aggregated tasks
across multiple projects
Before:
```
[error] TestError
[error] TestError
[error] (a/:sbtfixTest) TestError
[error] (b/:sbtfixTest) TestError
```
After:
```
[error] (a/sbtfixTest) TestError
[error] (b/sbtfixTest) TestError
```
Thanks @jvican for the help finding this.
=> Throw FeedbackProvidedError to avoid redundant logs

src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/root-validation/build.sbt, src/sbt-test/sbt-scalafix/root-validation/lib/src/main/scala/lib/App.scala, src/sbt-test/sbt-scalafix/root-validation/project/plugins.sbt, src/sbt-test/sbt-scalafix/root-validation/project/project/plugins.sbt, src/sbt-test/sbt-scalafix/root-validation/test
Previously, the semanticdb-scalac and scalacOptions validation ran for
empty root projects with no sources, failing the build when running
scalafix from the root project.  Since there are no sources to fix we
should not run any validation.
Fixes https://github.com/scalacenter/scalafix/issues/884
=> Skip validation if there are no sources to fix.

.jvmopts, src/main/scala/scalafix/internal/sbt/DependencyRule.scala, src/main/scala/scalafix/internal/sbt/ScalafixCompletions.scala, src/main/scala/scalafix/sbt/BuildInfo.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/dependency/.scalafix.conf, src/sbt-test/sbt-scalafix/dependency/build.sbt, src/sbt-test/sbt-scalafix/dependency/project/plugins.sbt, src/sbt-test/sbt-scalafix/dependency/project/project/plugins.sbt, src/sbt-test/sbt-scalafix/dependency/src/main/scala/A.scala, src/sbt-test/sbt-scalafix/dependency/test, src/test/scala/scalafix/internal/sbt/SbtCompletionsSuite.scala
To run a published rule directly from the sbt shell without modifying
build.sbt:
```
> scalafix dependency:SemanticRule@com.geirsson:example-scalafix-rule:1.3.0
```
=> Support one-line syntax for running published rules

src/main/scala/scalafix/sbt/ScalafixPlugin.scala
The projectSettings definition takes about 150ms to run on my laptop
during akka startup. It gets evaluated for each subproject in the build
which adds up. After this change, I found that the average time to load
akka dropped from roughly 19 seconds to 15.5 seconds.
=> Use lazy val instead of def

.scalafmt.conf, project/Dependencies.scala, src/main/scala/scalafix/internal/sbt/ScalafixCoursier.scala
The coursier-small module was created before the official
coursier/interface module was available. They both have the same goal,
expose a stable, zero dependency, API for fetching dependencies.  The
official API has the benefit of playing nicely with the official
coursier libraries when running concurrently.
The coursier/interface API is also richer, it for example supports
credentials, which is necessary to fix
https://github.com/scalacenter/scalafix/issues/984
We can't fully get rid of coursier-small yet since we use its types  in
the public API of sbt-scalafix. We should ideally deprecate the
coursier-small based settings down the road.
=> Migrate from coursier-small to coursier:interface

.travis.yml, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-1.3/semanticdb-enabled/.scalafix.conf, src/sbt-test/sbt-1.3/semanticdb-enabled/build.sbt, src/sbt-test/sbt-1.3/semanticdb-enabled/example/src/main/scala/example/Example.scala, src/sbt-test/sbt-1.3/semanticdb-enabled/project/build.properties, src/sbt-test/sbt-1.3/semanticdb-enabled/project/plugins.sbt, src/sbt-test/sbt-1.3/semanticdb-enabled/test
This PullRequest makes SemanticRules work through `semanticdbEnabled` settings which are [introduced in sbt 1.3](https://github.com/sbt/sbt/pull/4410).
With this change, Scalafix users will get the following benefits:
- Being able to add SemanticDB settings in `ThisBuild` scope. (In some cases, it would be handy.)
- Re-using SemanticDB settings of another tools, for sbt-scalafix as well. (It seems to be an expected use case of `semanticdbEnabled` key.)
While I adds sbt 1.3.x specific scripted test, it seems not to be invoked in sbt 0.13 scenario.
I believe its test is only for sbt 1.3 and can be ignored in sbt 0.13 case. If not, please let me know.
=> become compatible with sbt semanticdbEnabled settings

src/main/scala/scalafix/internal/sbt/SemanticRuleValidator.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/main/scala/scalafix/sbt/SemanticRuleValidator.scala, src/sbt-test/sbt-1.3/semanticdb-enabled/build.sbt
Following up of #89 , https://github.com/scalacenter/scalafix/pull/1094
Based on [this discussion](https://github.com/scalacenter/scalafix/pull/1094#discussion_r408247753), this PullRequest changes missing SemanticDB error message to ThisBuild configuration example if user sbt version is 1.3 or above.
=> Add ThisBuild recommendation settings to error message

src/main/scala/scalafix/internal/sbt/ScalafixCompletions.scala, src/main/scala/scalafix/internal/sbt/ShellArgs.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/explicit-files/test, src/test/scala/scalafix/internal/sbt/SbtCompletionsSuite.scala
The first time I used scalafix, it was through sbt, and I struggled to get it work on the shell while looking at https://scalacenter.github.io/scalafix/docs/users/installation.html#help.
The biggest frustration was the weird behavior or `rules` (the sbt section does advertize the use of the key/prefix-less syntax, but I missed it as I focused on the `man`-like help rather than the tutorial):
```
[root] $ scalafix --rules A --rules B
[error] (Compile / scalafix) scalafix.sbt.InvalidArgument: Unknown rule '--rules'
```
```
[root] $ scalafix --rules A B
[error] (Compile / scalafix) scalafix.sbt.InvalidArgument: the argument '--rules' requires a value but none was supplied
```
I got even more confused when I saw that tests used that syntax: …
=> Improve parser UX

src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/custom-config/.scalafixxx.conf, src/sbt-test/sbt-scalafix/custom-config/build.sbt, src/sbt-test/sbt-scalafix/custom-config/project/plugins.sbt, src/sbt-test/sbt-scalafix/custom-config/src/main/scala/example/Example.scala, src/sbt-test/sbt-scalafix/custom-config/test
Fixes https://github.com/scalacenter/scalafix/issues/1033
`RemoveUnused` was called without what's required for a semantic rule, as this default rule from the custom config was not picked up early enough, causing the choice to take the syntactic-only code path to be wrong.
=> take into account config file BEFORE checking if rules are syntactic

src/main/scala/scalafix/internal/sbt/ScalafixCoursier.scala, src/main/scala/scalafix/internal/sbt/ScalafixInterface.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/local-rules/build.sbt, src/sbt-test/sbt-scalafix/local-rules/project/plugins.sbt, src/sbt-test/sbt-scalafix/local-rules/rules/src/main/resources/META-INF/services/scalafix.v1.Rule, src/sbt-test/sbt-scalafix/local-rules/rules/src/main/scala/local/NoOp.scala, src/sbt-test/sbt-scalafix/local-rules/rules/src/test/scala/local/Boom.scala, src/sbt-test/sbt-scalafix/local-rules/sameproject/src/main/scala/Main.scala, src/sbt-test/sbt-scalafix/local-rules/sameproject/src/scalafix/resources/META-INF/services/scalafix.v1.Rule, src/sbt-test/sbt-scalafix/local-rules/sameproject/src/scalafix/scala/sameproject/NoOp.scala, src/sbt-test/sbt-scalafix/local-rules/service/src/main/scala/Main.scala, src/sbt-test/sbt-scalafix/local-rules/test, src/test/scala/scalafix/internal/sbt/ScalafixAPISuite.scala
In our fairly big sbt build, we have decided to collocate custom rule definitions with the sources they run against, using a separate sbt project of the same root build, in order to make the process of adding/updating them as seamless as possible (since they are not meant to be distributed or used anywhere else). It's working, but requires a quite hacky use of `--tool-classpath` which can only be passed once, with a lot of coursier-based code from here inlined.
This is an attempt at bringing the feature upstream (that I refer to in the code as "local rules"), although I assume it's not a very common use-case.
I chose to implement it using an ivy configuration (which might have some side-effects I didn't think of!). That led me to 2 interesting thoughts:
1. That configuration can be used …
=> Add support for rules defined/compiled within the same build

src/main/scala/scalafix/internal/sbt/LoggingOutputStream.scala, src/main/scala/scalafix/internal/sbt/ScalafixInterface.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/basic/build.sbt, src/sbt-test/sbt-scalafix/basic/test, src/test/scala/scalafix/internal/sbt/LoggingOutputStreamSuite.scala, src/test/scala/scalafix/internal/sbt/ScalafixAPISuite.scala
Diffs were dumped on stdout. When scalafix is run in parallel with many other tasks across multiple sub-projects, this makes it much easier to find out which files are the culprits and why, as the logs stand out and are available via `sbt last scalafix`.
Lint errors are already logged properly via https://github.com/scalacenter/sbt-scalafix/blob/v0.9.15-2/src/main/scala/scalafix/internal/sbt/ScalafixLogger.scala (and are not dumped to the `printStream` as far as I can tell, so we don't get duplicates).
=> log `scalafix --check` diffs as errors via a sbt logger

build.sbt, readme.md
Brice has made a lot of fantastic contributions lately improving the
experience of using sbt-scalafix for both end users and rule authors.
I'm really happy to welcome him as a sbt-scalafix maintainer!
=> Welcome Brice Jaglin to the team!

src/main/scala/scalafix/sbt/ScalafixPlugin.scala
Follow-up of https://github.com/scalacenter/sbt-scalafix/pull/100#discussion_r419377950
=> deprecate auto-exported `Scalafix` tag

src/main/scala/scalafix/sbt/BuildInfo.scala
https://github.com/scalacenter/sbt-scalafix/pull/116 triggered a warning, which turned into an error with https://github.com/scalacenter/sbt-scalafix/pull/114 that was merged right after without a rebase, causing `Release` and `CI` GitHub actions to fail on master.
=> remove unused val & import

src/main/scala/scalafix/internal/sbt/ScalafixCoursier.scala, src/main/scala/scalafix/internal/sbt/ScalafixInterface.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/basic/build.sbt, src/sbt-test/sbt-scalafix/local-rules/build.sbt
This is breaking binary compatibility, but preserves source compatibility via (deprecated) implicit conversion, which is always in scope for `*.sbt` sources, but require an explicit import for `*.scala`
sources, such as `import scalafix.sbt.ScalafixPlugin.autoImport._`.
That means that most 99% of direct sbt-scalafix users should be fine, but any plugin published against sbt-scalafix will need to be rebuilt.
Usage of coursierapi is a bit more cumbersome for sbt 0.13.x because the Java8 static methods in Repository cannot be used from Scala 2.10... As the scripted shows, it's still possible to setup resolvers without these helpers.
=> deprecate usage of coursiersmall type in scalafixResolvers

.github/workflows/ci.yml, src/sbt-test/sbt-scalafix/cross-build/build.sbt, src/sbt-test/sbt-scalafix/cross-build/project/ScalafixTestUtility.scala, src/sbt-test/sbt-scalafix/suppress/project/ScalafixTestUtility.scala
Follow-up of https://github.com/scalacenter/sbt-scalafix/commit/5f3934a1b300db5e3490154acc5aec9554a3386d which was not enforced in CI and where I missed the scripted sources.
=> make local dev possible with JDK11

src/main/scala/scalafix/sbt/ScalafixTestkitPlugin.scala, src/sbt-test/sbt-1.3/testkit/rules/src/main/scala/fix/Semantic.scala
The test for 4278a1f was too weak as it was not triggering the (lazy) lookup of semanticdb files.
This replicates [the behavior of `scalafix-cli`](https://github.com/scalacenter/scalafix/blob/v0.9.17/scalafix-cli/src/main/scala/scalafix/internal/v1/Args.scala#L316-L341), inspecting `scalacOptions` to detect a potential custom classpath for semanticdb files (set by default as `semanticdbIncludeInJar := false`).
https://github.com/sbt/sbt/blob/v1.3.12/main/src/main/scala/sbt/Defaults.scala#L469
=> support sbt 1.3.x SemanticdbPlugin in ScalafixTestkitPlugin (take 2)

src/main/scala/scalafix/internal/sbt/ScalafixCompletions.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/cross-build/test, src/sbt-test/sbt-scalafix/inconfig/test, src/sbt-test/skip-windows/caching/test, src/test/scala/scalafix/internal/sbt/SbtCompletionsSuite.scala
Docs companion: https://github.com/scalacenter/scalafix/pull/1160
Similarly to [`scalafmtAll`](https://github.com/scalameta/sbt-scalafmt/blob/v2.4.0/plugin/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala#L436) (except that the implementation here is more tricky as we deal with an `InputTask` for which [`.all`](https://www.scala-sbt.org/1.x/docs/Tasks.html#Getting+values+from+multiple+scopes) does not work), this allows a user to easily and efficiently run Scalafix across configurations for a given project (or of course for all projects/configurations with root project aggregation)
I saw there [were previous discussions/opinions about that](https://github.com/scalacenter/scalafix/pull/587#issuecomment-365218154) (I should have opened an issue to discuss that beforehand). From my side …
=> Introduce scalafixAll InputTask

src/sbt-test/sbt-scalafix/local-rules/build.sbt
Somehow, [this got lost](https://github.com/scalacenter/sbt-scalafix/compare/5316d91..fd97d1a#diff-989d991e5bc1817b8d9f0b2eef7af260) when I [addressed @olafurpg's comments](https://github.com/scalacenter/sbt-scalafix/pull/121#issuecomment-643939807). It demonstrates the second goal of https://github.com/scalacenter/sbt-scalafix/pull/121
> 2. Advanced users with local rules targeting 2.11 or 2.13 code will be able to simplify their build
=> test/document usage of local 2.13 rules

build.sbt, src/sbt-test/sbt-scalafix/basic/build.sbt, src/sbt-test/sbt-scalafix/basic/tests/src/test/scala/tests/CheckSuite.scala, src/sbt-test/sbt-scalafix/inconfig/build.sbt, src/sbt-test/sbt-scalafix/inconfig/tests/src/test/scala/tests/CheckSuite.scala
Supersedes #131 
Fixes the compile errors caused by using the deprecated `scala.meta.testkit.DiffAssertions`
=> Upgrade to Scalatest 3.2.0

src/main/scala/scalafix/internal/sbt/JGitCompletions.scala, src/test/scala/scalafix/internal/sbt/JGitCompletionsSuite.scala
Ref https://github.com/scalacenter/scalafix/issues/1196
Regression detected between 0.9.17 & 0.9.18, introduced by https://github.com/scalacenter/sbt-scalafix/pull/126
2ca68e4 exposed the failure to lookup commits during sbt initialization, while it would only happen on `scalafix` invocation earlier.
While looking at that, I initially thought 2ca68e4 changed the behavior by eagerly fetching the last commits into a setting, but [that lookup is memoized in a lazy val anyway](https://github.com/scalacenter/sbt-scalafix/blob/v0.9.17/src/main/scala/scalafix/internal/sbt/ScalafixCompletions.scala#L98-L99), so a `sbt reload` is required before or after 2ca68e4 to get an up-to-date list of commits.
=> prevent failure on sbt init when JGit finds a .git with no commit

src/main/scala/scalafix/internal/sbt/BlockingCache.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala
* The first commit fixes an embarrassingly massive performance regression introduced by 2ca68e4: the comment/assumption in https://github.com/scalacenter/sbt-scalafix/pull/126#discussion_r439692348 was wrong, causing artifact resolution & classloader creation to happen for each invocation/project/configuration, which caused slow startup and slower rule execution (JIT not warmed up). It might also fix https://github.com/scalacenter/scalafix/issues/1196#issuecomment-654744979.
* The second commit brings back the 0.9.17 behavior of looking up last commits for the parser at the first `scalafix` invocation (changed also in 2ca68e4), to reduce the risk of JGit stuff blocking the initialization like https://github.com/scalacenter/scalafix/issues/1196. Related to …
=> Fix 0.9.18 caching/performance regressions

src/main/scala/scalafix/internal/sbt/ScalafixInterface.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala
https://github.com/scalacenter/sbt-scalafix/pull/142#discussion_r450829771
=> prefer URI over URL for keys to avoid hostname resolution on equals 

src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/skip-windows/caching/test
https://github.com/scalacenter/scalafix/issues/1164#issuecomment-656567498
If a file is patched during a scalafix run, it's not safe to assume that all rules observed the updated content of that file and thus can
be skipped next time. It is if we have only one rule (which we could check) or if the patch is applied after the first rule (which we can't tell). For correctness, stamping should happen before rule execution.
=> caching: remove optimization bringing false positive cache hits

src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/scalafixOnCompile/.scalafix.conf, src/sbt-test/sbt-scalafix/scalafixOnCompile/build.sbt, src/sbt-test/sbt-scalafix/scalafixOnCompile/lint/src/test/scala/Null.scala, src/sbt-test/sbt-scalafix/scalafixOnCompile/project/plugins.sbt, src/sbt-test/sbt-scalafix/scalafixOnCompile/rewrite/src/it/scala/UnusedImports.scala, src/sbt-test/sbt-scalafix/scalafixOnCompile/rewrite/src/main/scala/UnusedImports.scala, src/sbt-test/sbt-scalafix/scalafixOnCompile/test
Users can control whether Scalafix should be run (with the rules defined in `.scalafix.conf`) as part of `compile,`at the project & configuration level.
The value of `scalafixOnCompile` is ignored when invoking directly `scalafix` or `scalafixAll`, as the CLI arguments (if there are any) take precedence over the default rules. That means for example that `scalafix --check` is safe to run even though `scalafixOnCompile := true`, as there will not be any rewrite triggered by the implicit compilation.
Enabling `scalafixOnCompile` wil automatically turn on caching, which can be disabled by an explicit `scalafixCaching := false`.
=> scalafixOnCompile setting key

src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/wrapper/.scalafix.conf, src/sbt-test/sbt-scalafix/wrapper/build.sbt, src/sbt-test/sbt-scalafix/wrapper/project/LintAllPlugin.scala, src/sbt-test/sbt-scalafix/wrapper/project/plugins.sbt, src/sbt-test/sbt-scalafix/wrapper/src/main/scala/example/Example.scala, src/sbt-test/sbt-scalafix/wrapper/src/main/scala/imported/Imported.scala, src/sbt-test/sbt-scalafix/wrapper/test
Regression of 0cf5501: initial (cold) invocations to a task delegating to `scalafix` would result in `scalafix` being called before compilation (because `scalafixRunExplicitly == false`) causing false negatives.
This makes sure compilation is always triggered before `scalafix` (no matter how it's called), but depends on the final sub-tak of `compile` in a cycle-free way.
=> fix usage of scalafix via another task

src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/scalafixResolvers/.env, src/sbt-test/sbt-scalafix/scalafixResolvers/build.sbt, src/sbt-test/sbt-scalafix/scalafixResolvers/project/plugins.sbt, src/sbt-test/sbt-scalafix/scalafixResolvers/test
The impetus for this proposed change is trying to use privately hosted `scalafix` rules with [`scala-steward`](https://github.com/scala-steward-org/scala-steward). Currently, the scalafix tutorial describes how to [add custom scalafix resolvers](https://scalacenter.github.io/scalafix/docs/developers/tutorial.html#adding-custom-resolver) in a project's `build.sbt`. Since scala-steward adds the sbt-scalafix plugin on the fly, however, it would further need to edit a project's `build.sbt` in order to add custom resolvers, which would be tricky.
The alternative I'm proposing here sets the `scalafixResolvers` to Coursier's [`defaultRepositories`](https://github.com/coursier/coursier/blob/master/modules/coursier/jvm/src/main/scala/coursier/PlatformResolve.scala#L19).  The …
=> Change scalafixResolvers to come from Coursier defaults so can be overridden

src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/basic/build.sbt, src/sbt-test/sbt-scalafix/cross-build/build.sbt, src/sbt-test/sbt-scalafix/inconfig/build.sbt, src/sbt-test/sbt-scalafix/scalafixOnCompile/build.sbt
Hello - 
Upgrading to sbt-scalafix 0.9.19 caused one of my projects to fail. When poking around, I noticed that the new `scalafixOnCompile` configuration setup did not respect the configuration that was passed into the `scalafixConfigSettings` function. 
The scripted test got around this by doing `inConfig(IntegrationTest)(scalafixConfigSettings(IntegrationTest))`. You should be able to just do ` scalafixConfigSettings(IntegrationTest)`. 
This PR updates the `scalafixConfigSettings` function to respect the passed `Configuration` value for these items.
=> Respect Configuration in scalafixConfigSettings

src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/concurrency/build.sbt, src/sbt-test/sbt-scalafix/concurrency/project/plugins.sbt, src/sbt-test/sbt-scalafix/concurrency/src/main/scala/example/Example.scala, src/sbt-test/sbt-scalafix/concurrency/src/scalafix/scala/fix/AddFooter.scala, src/sbt-test/sbt-scalafix/concurrency/test
When rewrite rules are executed, `scalafix` and `scalafixAll` may conflict with other tasks transforming `unmanagedSources`. Since there is no way to identify such tasks given the sbt model, and to be defensive against this scenario, `scalafix` tasks may only run concurrently with other `scalafix` tasks, but not with any other tasks.
For explicit invocations, this should not damage throughput, but for complex builds with `scalafixOnCompile := true`, this can have a limited impact during the first compile; after that caching should make it negligible.
=> prevent concurrent modifications of sources by limiting concurrency

src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/custom-src-directory/app/ProcedureSyntax.scala, src/sbt-test/sbt-scalafix/custom-src-directory/build.sbt, src/sbt-test/sbt-scalafix/custom-src-directory/project/plugins.sbt, src/sbt-test/sbt-scalafix/custom-src-directory/test
When defining local rules using the Scalafix configuration, libraryDependencies must be defined, as documented in: https://scalacenter.github.io/scalafix/docs/developers/local-rules.html. We could add it by default, but it would unnecessarily clutter the update task in 99.9% of the plugin use cases.
When projects have a custom directory layout (via scalaSource), users could not know that Scalafix settings would need to be updated to exclude sources potentially at the root (sourcesInBase), in order to prevent compilation errors as Scalafix does not have the Scala libs, causing:
> scala.reflect.internal.MissingRequirementError: object scala in compiler mirror not found.
This commit disables sourcesInBase by default to prevent this, as the local rules have no reason to share code with other …
=> support running scalafix on projects with sources at the root

.gitignore, build.sbt, src/main/scala-sbt-0.13/sbt/internal/sbtscalafix/Caching.scala, src/main/scala-sbt-1.0/sbt/internal/sbtscalafix/Caching.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala
The objective is to produce a machine-independent cache in order to include sbt-scalafix cache files in the [remote cache artifact](https://www.scala-sbt.org/1.x/docs/Remote-Caching.html).
Two things are missing:
1. Cache stamps must be persisted with relative paths instead of absolute paths (https://github.com/sbt/sbt/issues/6298)
1. sbt-scalafix have to use `hash` instead of `lastModified` style for cache stamping.
This PR solves the second point.
To make the scripted tests green, i had to permit to get back the previous behaviour (`lastModified`). Done with a system property.
=> Toward a machine-independent incremental cache file

src/main/scala/scalafix/sbt/ScalafixPlugin.scala
Since https://github.com/scalacenter/sbt-scalafix/pull/188 the scalafix is _almost_ machine-independent but we discovered that the `args` was not determinist across machines. 
This PR fixes this issue by sorting the classpath and the dependencies before hashing them.
=> Deterministic `args` file stamp

src/main/scala/scalafix/sbt/ScalafixEnable.scala, src/sbt-test/sbt-scalafix/scalafixEnable/build.sbt, src/sbt-test/sbt-scalafix/scalafixEnable/scala212/src/main/scala/UnusedImportAndProcedureSyntax.scala, src/sbt-test/sbt-scalafix/scalafixEnable/test
Closes https://github.com/scalacenter/scalafix/issues/1346
`scalafixEnable` should maximize the chances of getting `semanticdb-scalac` to run so that semantic rules can run.
When enabled in the build, `-Xfatal-warnings` can be a major obstacle for example when:
1. `scalafixEnable` forced a newer (patch) Scala version that the one in the build, with improved warning reporting;
2. the user already has a build with fatal deprecation warnings and wants to apply a rewrite rule to fix them.
=> scalafixEnable: relax -Xfatal-warnings for scalafix invocations

src/main/scala-sbt-0.13/sbt/internal/sbtscalafix/Compat.scala, src/main/scala-sbt-1.0/sbt/internal/sbtscalafix/Compat.scala, src/main/scala/scalafix/sbt/ScalafixEnable.scala, src/sbt-test/sbt-scalafix/scalafixEnable/build.sbt, src/sbt-test/sbt-scalafix/scalafixEnable/project/FatalWarningsPlugin.scala
Also, scalacOptions are now set in a more specific scope (matching the one looked up for compiler invocation so that scalafixEnable overrides them no matter at which scope they are defined), so assertions had to be updated.
Fixes https://github.com/scalacenter/scalafix/issues/1306
=> scalafixEnable: support builds overriding scalacOptions

.scalafmt.conf, project/Dependencies.scala, src/main/scala/scalafix/internal/sbt/BlockingCache.scala, src/main/scala/scalafix/internal/sbt/LoggingOutputStream.scala, src/main/scala/scalafix/internal/sbt/SemanticRuleValidator.scala, src/main/scala/scalafix/internal/sbt/SemanticdbPlugin.scala, src/main/scala/scalafix/sbt/ScalafixEnable.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-1.5/scala-3/build.sbt, src/sbt-test/sbt-1.5/scala-3/project/build.properties, src/sbt-test/sbt-1.5/scala-3/project/plugins.sbt, src/sbt-test/sbt-1.5/scala-3/src/main/scala/SignificantIndentation.scala, src/sbt-test/sbt-1.5/scala-3/test, src/sbt-test/sbt-1.5/scalafixEnable/build.sbt, src/sbt-test/sbt-1.5/scalafixEnable/project/build.properties, src/sbt-test/sbt-1.5/scalafixEnable/project/plugins.sbt, src/sbt-test/sbt-1.5/scalafixEnable/scala210/src/main/scala/Main.scala, src/sbt-test/sbt-1.5/scalafixEnable/scala211/src/main/scala/Main.scala, src/sbt-test/sbt-1.5/scalafixEnable/scala3/src/main/scala/SignificantIndentation.scala, src/sbt-test/sbt-1.5/scalafixEnable/test
Showcases https://github.com/scalacenter/scalafix/pull/1392
See open questions / limitations in https://github.com/scalacenter/scalafix/issues/1316#issuecomment-839074644
**Note that most of the [built-in Scalafix rules](https://scalacenter.github.io/scalafix/docs/rules/overview.html) do not support Scala 3 sources at the moment.**
=> initial support for running rules on Scala 3 sources

project/Dependencies.scala, src/main/scala/scalafix/sbt/ScalafixTestkitPlugin.scala, src/sbt-test/sbt-1.3/semanticdb-enabled/project/plugins.sbt, src/sbt-test/sbt-1.3/testkit/tests/src/test/scala/fix/InputOutputSuite.scala, src/sbt-test/sbt-1.5/scala-3/project/plugins.sbt, src/sbt-test/sbt-1.5/scalafixEnable/project/plugins.sbt, src/sbt-test/sbt-scalafix/basic/build.sbt, src/sbt-test/sbt-scalafix/concurrency/build.sbt, src/sbt-test/sbt-scalafix/local-rules/build.sbt, src/sbt-test/sbt-scalafix/testkit/tests/src/test/scala/fix/InputOutputSuite.scala, src/test/scala/scalafix/internal/sbt/SbtCompletionsSuite.scala, src/test/scala/scalafix/internal/sbt/ScalafixAPISuite.scala
Follows https://github.com/scalacenter/sbt-scalafix/pull/210
It's useful to build and run all scripted tests against a scalafix SNAPSHOT to avoid getting (late) surprises during the 2-step (scalafix/sbt-scalafix) release phase.
Most of the users running SNAPSHOT versions of sbt-scalafix should be able to use one that depends on a SNAPSHOT scalafix since they must already have sonatype snapshots in the metabuild and the default `scalafixResolvers` will re-resolve scalafix through sonatype snapshots via the embedded coursier.
=> make it possible to and do build against a scalafix SNAPSHOT

src/main/scala/scalafix/internal/sbt/ScalafixInterface.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala
We are backpedaling from https://github.com/scalacenter/scalafix/issues/1108#issuecomment-647402044 at the light of the strategy we will most likely chose for `ExplicitResultTypes` on Scala 3: https://github.com/scalacenter/scalafix/issues/1316.
=> print actionnable error when trying to resolve Scala 3 scalafix

src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/skip-windows/caching/build.sbt
The lack of bug reports over the last year or so, despite usage of it through `scalafixOnCompile` (see https://github.com/scalacenter/scalafix/issues/1164#issuecomment-791379286 & https://github.com/search?p=3&q=scalafixOnCompile&type=Code) makes me believe the feature is mature enough for prime time. In real life, we never experienced the false positive mentioned in https://github.com/scalacenter/scalafix/issues/1164#issue-639185750, and since CI should run on a clean slate anyway, I think it's safe to say that it's only a theoretical concern.
Ideally, it should move to upstream scalafix, but handling state & file stamping without sbt helpers is far from trivial.
=> enable scalafixCaching by default

src/main/scala-sbt-1.0/scalafix/sbt/ScalafixTestkitPlugin.scala, src/sbt-test/sbt-1.5/testkit/build.sbt, src/sbt-test/sbt-1.5/testkit/test
Follows https://github.com/scalacenter/sbt-scalafix/pull/219
=> ScalafixTestkitPlugin improvements

project/Dependencies.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-1.5/testkit/build.sbt, src/sbt-test/sbt-1.5/testkit/input/src/main/scala-2.13/fix/Source3.scala, src/sbt-test/sbt-1.5/testkit/output/src/main/scala-2.13/fix/Source3.scala, src/sbt-test/sbt-1.5/testkit/test, src/sbt-test/sbt-scalafix/cross-build/213.scalafix.conf, src/sbt-test/sbt-scalafix/cross-build/build.sbt, src/sbt-test/sbt-scalafix/cross-build/scala213/src/main/scala/Source3.scala, src/test/scala/scalafix/internal/sbt/SbtCompletionsSuite.scala
https://github.com/scalacenter/scalafix/pull/1408
https://github.com/scalacenter/scalafix/pull/1409
=> Scala 2.13.6 & -Xsource:3 support

src/main/scala/scalafix/sbt/ScalafixPlugin.scala
The Scalafix config adds a BSP build target that is useless because it has no sources.
This PR disables BSP in the Scalafix config so that it is never exported to the IDE. The implementation involves a bit of reflection to deal with the compatibility issue on old versions of sbt.
See also:
- https://github.com/sbt/sbt/issues/6546
- https://github.com/scalameta/metals/pull/2895
=> Disable BSP in Scalafix config

src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/relax-scalacOptions/build.sbt, src/sbt-test/sbt-scalafix/relax-scalacOptions/src/main/scala/IgnoreWarning.scala
Creating this to start a conversation about it and to see if this would be alright as a follow-up to some of the work done in https://github.com/scalacenter/sbt-scalafix/pull/196. If I understood the conversation right you want to avoid situations where this is set to error out causing issues. However, currently it strips out any usage of `-Wconf`. The situation that I'm in is that we want to avoid warnings from generated sources since we generate a _ton_ of files with scalaxb that contains a whole bunch of compiler warnings.  To silence these we use `-Wconf:src=src_managed/.*:silent`. This works great during normal compilation, but then when we run scalafix check in our CI our logs end up being full or warnings causing a scare. Would it be possible to make this more fine-grained like …
=> Add more fine grained check for `scalacOptionsToRelax`

build.sbt, readme.md, src/main/scala/scalafix/sbt/ScalafixTestkitPlugin.scala
- Fixes https://github.com/scalacenter/scalafix/issues/1535 (first commit)
- Document in second commit what https://github.com/scalacenter/sbt-scalafix/pull/211 was already about
- Convenience addition in third commit, allowing
- https://github.com/scalacenter/scalafix/pull/1537 
- https://github.com/scalacenter/scalafix.g8/pull/68
=> don't force sonatypeSnapshots on all ScalafixTestkitPlugin users

src/main/scala/scalafix/internal/sbt/DependencyRule.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/dependency/build.sbt, src/sbt-test/sbt-scalafix/dependency/src/test/scala/B.scala, src/sbt-test/sbt-scalafix/dependency/test
Rationale: the `::` syntax is now standard in scala tooling to designate scala artifacts
Docs companion: https://github.com/scalacenter/scalafix/pull/1542
=> support and favor ammonite/coursier syntax for dependency:

project/Dependencies.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/basic/build.sbt
0.10.0 is ahead because of https://github.com/scalacenter/scalafix/pull/1565, so it's a good occasion to clean up!
=> remove deprecated keys

src/main/scala/scalafix/internal/sbt/Implicits.scala, src/main/scala/scalafix/internal/sbt/ScalafixInterface.scala, src/main/scala/scalafix/sbt/ScalafixEnable.scala, src/sbt-test/sbt-scalafix/dependency/build.sbt, src/sbt-test/sbt-scalafix/scalafixEnable/build.sbt, src/sbt-test/sbt-scalafix/scalafixEnable/project/plugins.sbt
1. Keep the build scala version when semanticdb-scalac is available for that scala version for the scalameta version that scalafix tracks.
1. If not, try to find the earliest binany-compatible semanticdb-scalac (preferred over the latest last to be more repeatable) and use it instead.
1. Only when that fails (or resolution fails), force the scala version as previously.
(1) avoids unnecessary scala bumps which can result in
- zinc cache invalidation
- compilation failures because of stricter compiler checks
- resolution failures because of yet-unpublished compiler plugins (fixes https://github.com/scalacenter/scalafix/issues/1573)
(2) opens the possibility for using sbt-scalafix on scala versions released "in the future" without any scalameta/scalafix bump (as long as scalameta is …
=> make scalafixEnable less aggressive & more future-proof

src/main/scala/scalafix/internal/sbt/ScalafixInterface.scala
Follows https://github.com/scalacenter/scalafix/pull/1565/files#r825365856
```diff
sbt> scalafix dependency:SemanticRule@ch.epfl.scala::example-scalafix-rule:1.4.0
-Loading external rule(s) built against an old version of scalafix (0.9.16).
-This might not be a problem, but if you run into unexpected behavior, you should either:
-1. downgrade scalafix to 0.9.16
-2. try a more recent version of the rules(s) if available; request the rule maintainer
-   to build against scalafix 0.10.0 or later if that does not help
+[info] Loading external rule(s) built against an old version of scalafix (0.9.16).
+[info] This might not be a problem, but if you run into unexpected behavior, you should either:
+[info] 1. downgrade scalafix to 0.9.16
+[info] 2. try a more recent version of the rules(s) if …
```
=> wire scalafix initialization logs to proper logger

src/main/scala/scalafix/sbt/ScalafixEnable.scala, src/sbt-test/sbt-scalafix/scalafixEnable/build.sbt, src/sbt-test/sbt-scalafix/scalafixEnable/test
Regression of https://github.com/scalacenter/sbt-scalafix/pull/292
Found via https://github.com/scalameta/munit/pull/513
Addresses a special case of https://github.com/scalacenter/scalafix/issues/986 (https://github.com/sbt/sbt/issues/5459 does not seem to apply after `++`)
=> scalafixEnable: preserve versions set by ++

src/main/scala/scalafix/internal/sbt/ScalafixInterface.scala
Towards https://github.com/scalacenter/scalafix/issues/1622
=> don't swallow stack traces on unchecked exception

project/Dependencies.scala
Effectively revert https://github.com/coursier/interface/commit/03ce01c612665ed7d2d7ffe0ad32395b39d5e099, to avoid problem highlighted by https://github.com/scalacenter/scalafix/pull/1718#issuecomment-1369225217
=> don't force slf4j 2

src/sbt-test/sbt-scalafix/scalafixEnable/project/FatalWarningsPlugin.scala
https://github.com/scalacenter/sbt-scalafix/commit/30d8d4d950a2e8741d7c89d87d7bb3a4b7b604b1#diff-99217f6aaf66894a50a0dfb21ae350532d758c711dbcbd670ae6249bc965317a already documented that [the feature](https://github.com/scalacenter/sbt-scalafix/pull/203) was not working with sbt 1.3.x and later, so [now that earlier versions are no longer tested/supported](https://github.com/scalacenter/sbt-scalafix/pull/291), we should kill the dead branch of the test.
=> overriden scalacOptions are not supported by scalafixEnable

src/sbt-test/sbt-1.5/testkit/tests/src/test/scala/fix/InputOutputSuite.scala
Fix "expected" failure introduced after rushing https://github.com/scalacenter/sbt-scalafix/pull/348 out for the 0.11.0 release, caused by https://github.com/scalacenter/scalafix/pull/1750.
=> fix test relying on ScalaTest 3.0.x

project/Dependencies.scala
Closes https://github.com/scalacenter/scalafix/issues/1860
Official release will follow before Monday Sep 11th.
=> Latest scalafix SNAPSHOT for scala 2.13.12 support

project/Dependencies.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-1.5/testkit/build.sbt, src/sbt-test/sbt-scalafix/basic/build.sbt, src/sbt-test/sbt-scalafix/inconfig/build.sbt, src/sbt-test/sbt-scalafix/root-validation/build.sbt, src/sbt-test/sbt-scalafix/semanticdb-enabled/build.sbt, src/sbt-test/sbt-scalafix/unavailable-semanticdb-scalac/build.sbt, src/sbt-test/sbt-scalafix/unavailable-semanticdb-scalac/project/plugins.sbt, src/sbt-test/sbt-scalafix/unavailable-semanticdb-scalac/test, src/sbt-test/skip-java17/scalafixResolvers/build.sbt
Follows https://github.com/scalacenter/scalafix/pull/1857
Since https://github.com/scalameta/scalameta/pull/3250, [semanticdb-scalac](https://mvnrepository.com/artifact/org.scalameta/semanticdb-scalac) is no longer published for all patch releases of Scala 2.13 and most patch releases of Scala 2.12, but only the 4 latest for each.
`scalafixEnable` is able to lookup a suitable scalameta version as of https://github.com/scalacenter/sbt-scalafix/pull/292, but "permanent" sbt-scalafix / Scala 2.x users, leveraging sbt's SemanticdbPlugin via
```diff
+    semanticdbEnabled := true, // enable SemanticDB
+    semanticdbVersion := scalafixSemanticdb.revision // only required for Scala 2.x
```
[per the documentation](https://github.com/scalacenter/scalafix/blob/f4dcc6fa889c4a03f71881b3b6ac962bde59c2 …
=> better error reporting when semanticdb-scalac is not found

src/sbt-test/sbt-scalafix/explicit-files/test
Follows https://github.com/scalacenter/sbt-scalafix/pull/378 & https://github.com/scalacenter/scalafix/issues/1874
The sbt behavior or completions for aggregating tasks (typically `scalafix` on the root project) is interesting as all aggregated projects contribute to the possible completion values.
* everything goes well if at one (resp. several) aggregated project(s) can validate all the arguments, in which case that one runs (resp. these ones run) and the others are silently skipped
* if provided several arguments valid each of them in one different aggregated project, the invocation will fail, showing the validation error on the aggregating project.
=> document weird behavior

src/main/scala/scalafix/sbt/ScalafixPlugin.scala
Follows https://github.com/scalacenter/sbt-scalafix/pull/380
Similar to https://github.com/scalacenter/scalafix/pull/1907
=> docs: ScalafixInterface is now at project-level

src/main/scala/scalafix/internal/sbt/ScalafixInterface.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/test/scala/scalafix/internal/sbt/SbtCompletionsSuite.scala, src/test/scala/scalafix/internal/sbt/ScalafixAPISuite.scala
Towards https://github.com/scalacenter/scalafix/issues/951
=> add `scalafixCallback` setting key to customize diagnostics reporting

build.sbt
It seems that https://github.com/scalacenter/sbt-scalafix/commit/a619fb7d02bef70116b85c65dc0c7ae9674cb8e8#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91 is no longer required (on recent sbt versions?)
=> old sbt versions can run on recent JDKs when loaded with scripted

.github/workflows/ci.yml, build.sbt, src/sbt-test/sbt-scalafix/dependency/build.sbt, src/sbt-test/sbt-scalafix/local-rules/build.sbt, src/sbt-test/sbt-scalafix/local-rules/test, src/sbt-test/skip-windows/caching/build.sbt, src/sbt-test/skip-windows/caching/test
Follows https://github.com/scalacenter/sbt-scalafix/pull/391 & https://github.com/scalacenter/sbt-scalafix/pull/395
Partially reverts https://github.com/scalacenter/sbt-scalafix/pull/393
=> fix JDK21 CI

src/main/scala/scalafix/internal/sbt/ScalafixCompletions.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/test/scala/scalafix/internal/sbt/SbtCompletionsSuite.scala
Maybe partially(?) fix https://github.com/scalacenter/scalafix/issues/1965 if there are many sub projects
if there is example sbt project as follow
```scala
lazy val p1 = project
lazy val p2 = project
lazy val p3 = project
lazy val p4 = project.disablePlugins(ScalafixPlugin)
```
(`p1` + `p2` + `p3` + `implicit root project`) * ( `Compile/scalafix` + `Test/scalafix` + `scalafixAll` )
= 4 * 3
= 12`JGitCompletion` instances
only one `JGitCompletion` instance
=> add `scalafixJGitCompletion` key. reduce memory usage

src/main/scala/scalafix/internal/sbt/JGitCompletions.scala
- https://github.com/scalacenter/scalafix/issues/1965#issuecomment-2016445243
=> fix JGitCompletions memory leak

src/main/scala/scalafix/sbt/ScalafixPlugin.scala
Follows https://github.com/scalacenter/sbt-scalafix/pull/404
=> docs: scalafixResolvers can only be set at ThisBuild level

src/main/scala/scalafix/internal/sbt/BlockingCache.scala, src/main/scala/scalafix/internal/sbt/ScalafixCompletions.scala, src/main/scala/scalafix/internal/sbt/ScalafixInterface.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/test/scala/scalafix/internal/sbt/SbtCompletionsSuite.scala, src/test/scala/scalafix/internal/sbt/ScalafixAPISuite.scala
[Code review](https://github.com/scalacenter/sbt-scalafix/pull/404#discussion_r1566477171) showed that we have several types of memoization since https://github.com/scalacenter/sbt-scalafix/pull/380. It turns that we have actually 3 different types of caching at the moment:
1. [a basic `LazyValue` memoizer](https://github.com/scalacenter/sbt-scalafix/commit/4dbaf1ece9a67ab686cf5c4e12483298996005de), effectively useless since https://github.com/scalacenter/sbt-scalafix/pull/380 given how it's used
1. [a companion-object-bound cache](https://github.com/scalacenter/sbt-scalafix/pull/380), to amortize the cost of repeated invocations
1. [a task-bound cache](https://github.com/scalacenter/sbt-scalafix/commit/89cfd04629a6c67d3110e073c1c9948675c85a37), to amortize a single invocation across …
=> centralize ScalafixInterface memoization within a setting key

build.sbt, src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/relax-scalacOptions/build.sbt, src/sbt-test/sbt-scalafix/relax-scalacOptions/test
Follow-up of https://twitter.com/channingwalton/status/1778119590486118908 which puts the finger on a behavior that can be very irritating in large builds
> TIL [#scala](https://twitter.com/hashtag/scala?src=hashtag_click) [#protip](https://twitter.com/hashtag/protip?src=hashtag_click) Scalafix. 
> 
> If you put “scalafix —check” before other steps in your sbt build, your code might get compiled twice. 
> 
> Put it after compilation steps to avoid the problem.
This revisits https://github.com/scalacenter/sbt-scalafix/pull/152, leveraging `scalafixInvoked` (which has the same semantics as the `scalafixRunExplicitly` mentioned in the old PR but didn't cause any issue for [3 years](https://github.com/scalacenter/sbt-scalafix/pull/196)) in order to trigger a regular `compile` from `scalafix` …
=> avoid full (re)compilation after cold scalafix invocations

src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-1.5/scalafixEnable/test, src/sbt-test/sbt-1.5/testkit/test, src/sbt-test/sbt-scalafix/basic/test, src/sbt-test/sbt-scalafix/cross-build/test, src/sbt-test/sbt-scalafix/custom-src-directory/test, src/sbt-test/sbt-scalafix/inconfig/test, src/sbt-test/sbt-scalafix/local-rules/test, src/sbt-test/sbt-scalafix/relax-scalacOptions/test, src/sbt-test/sbt-scalafix/root-validation/test, src/sbt-test/sbt-scalafix/scalafixEnable/test, src/sbt-test/sbt-scalafix/scalafixOnCompile/test, src/sbt-test/sbt-scalafix/semanticdb-enabled/test, src/sbt-test/sbt-scalafix/suppress/test, src/sbt-test/skip-windows/caching/test
- https://github.com/sbt/sbt/pull/6309
=> avoid deprecated old shell syntax

project/plugins.sbt
Follows https://github.com/scalacenter/sbt-scalafix/pull/428
See https://github.com/xerial/sbt-sonatype/issues/507
The regression is not visible on master  as the new client is apparently not used for OSS snapshots.
=> bump sbt-ci-release to fix JDK8 support

src/main/scala/scalafix/internal/sbt/ScalafixInterface.scala, src/main/scala/scalafix/sbt/ScalafixPlugin.scala
Fix regression introduced in https://github.com/scalacenter/sbt-scalafix/commit/9ad48bbee83f56696ee9e6b645b21fdea50c6313: sbt-scalafix wouldn't catch usage of Scala 2.11, resulting in a non-actionnable error message.
=> fix Scala 2.11 detection & use same instance across patch releases

src/main/scala/scalafix/internal/sbt/BlockingCache.scala, src/main/scala/scalafix/internal/sbt/ScalafixInterface.scala
Scalafix instances can be memory-consuming (PrintStream's static 8k BufferedWriter allocations are wasteful and hard to remove for example), so this allow eviction in case of memory pressure.
To compensate for the added complexity, the implementation was simplified.
* Values are now always updated (even if they haven't changed). This probably does not change much performance-wise, as we are trading throwing an exception (costly) against a SoftReference instanciation and the update in the low-cardinality ConcurrentHashMap.
* SAM conversion is used now that sbt 0.13 / Scala 2.11 are no longer supported.
=> evict cached Scalafix instances under memory pressure

.github/workflows/release.yml
~Fix regression introduced in https://github.com/scalacenter/sbt-scalafix/pull/414 (impacting 0.12.1 & 0.13.0)~
... actually https://github.com/scalacenter/sbt-scalafix/blob/9f32b14f26d952659f8758f5b469e86db16a438d/build.sbt#L66 is enough, but better safe than sorry!
=> make sure sbt-scalafix is published with JDK8 bytecode

src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/unavailable-semanticdb-scalac/build.sbt
Hey there! Recently, I've been upgrading some dependencies of one project and accidentally got this error message in SBT:
> The SemanticDB scalac plugin version 4.9.3 set up via `semanticdbVersion` does follow the version recommended for Scalafix, but is not supported for the outdated Scala version 2.13.16. Please upgrade to a more recent Scala patch version or uninstall sbt-scalafix.
Honestly, it's a bit confusing since Scala 2.13.16 is the most recent version of the 2.13 series. What I actually had to do was update the sbt-scalafix version to the latest one.
So, here's the enhancement of that error message.
=> Enhance error message when SemanticDB scalac plugin can't be found

build.sbt, src/main/scala-3/scalafix/internal/sbt/SemanticdbCachingWorkaroundPlugin.scala
Brings in https://github.com/sbt/sbt/pull/8086 until fixed upstream
=> workaround bug on builds handled by sbt 2.0.0-M4

src/main/scala/scalafix/sbt/ScalafixPlugin.scala, src/sbt-test/sbt-scalafix/skip/.scalafix.conf, src/sbt-test/sbt-scalafix/skip/project/plugins.sbt, src/sbt-test/sbt-scalafix/skip/src/main/scala/Null1.scala, src/sbt-test/sbt-scalafix/skip/src/test/scala/Null2.scala, src/sbt-test/sbt-scalafix/skip/test, src/sbt-test/skip-sbt1.4/scalafixEnable/test
Fixes https://github.com/scalacenter/scalafix/issues/1413
- add support for skip at project / conf / task levels
- rely on that to skip unsupported projects
=> gracefully ignore projects with unsupported binary version
